# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#

setenv load_addr "0x9000000"
setenv overlay_error "false"
# default values
setenv rootdev "/dev/mmcblk0p1"
setenv verbosity "1"
setenv console "both"
setenv bootlogo "false"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "off"

test -n "${distro_bootpart}" || distro_bootpart=1

echo "Boot script loaded from ${devtype} ${devnum}:${distro_bootpart}"

# ---- LB2004: no PMIC I2C hack (board has no RK809 on I2C0 for vdd_npu) ----

if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}armbianEnv.txt; then
	load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} ${prefix}armbianEnv.txt
	env import -t ${load_addr} ${filesize}
fi

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS2,1500000 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlycon ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}"
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

# get PARTUUID of first partition on SD/eMMC the boot script was loaded from
if test "${devtype}" = "mmc"; then part uuid mmc ${devnum}:${distro_bootpart} partuuid; fi

# LB2004: force single-core boot. The v1.25 DDR blob (only one that doesn't
# hang on eyescan) mis-trains for multi-core: CPU1 hard-locks during
# secondary_start_kernel and watchdog panics at ~24s. maxcpus=1 keeps the
# board usable; revisit when a multi-core-safe DDR blob is found.
setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} ubootpart=${partuuid} usb-storage.quirks=${usbstoragequirks} maxcpus=1 ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"; fi

load ${devtype} ${devnum}:${distro_bootpart} ${ramdisk_addr_r} ${prefix}uInitrd
load ${devtype} ${devnum}:${distro_bootpart} ${kernel_addr_r} ${prefix}Image

load ${devtype} ${devnum}:${distro_bootpart} ${fdt_addr_r} ${prefix}dtb/${fdtfile}

if test -n "${overlays}"; then
	for overlay in ${overlays}; do
		echo "Loading overlay ${overlay}"
		load ${devtype} ${devnum}:${distro_bootpart} ${fdtoverlay_addr_r} ${prefix}dtb/overlay/${overlay}.dtbo || setenv overlay_error "true"
		fdt addr ${fdt_addr_r}
		fdt resize 65536
		fdt apply ${fdtoverlay_addr_r} || setenv overlay_error "true"
	done
fi

if test "${overlay_error}" = "true"; then
	echo "Overlay apply failed, ignoring..."
fi

booti ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}
