name: Run build train on config changes
on:
  push:
    branches:
      - 'main'
    paths:
      - 'config/*.config'
      - 'config/boards/*.conf'
      - 'config/boards/*.csc'
      - 'config/boards/*.wip'
      - 'config/boards/*.eos'
      - 'config/boards/*.tvb'
      - 'config/kernel/*.config'
      - 'config/sources/families/*.conf'
      - 'config/bootenv/*.cmd'
      - 'patch/**'

jobs:

  Run:
    name: "Execute workflow"
    if: ${{ github.repository_owner == 'Armbian' }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: armbian/os
          event-type: "Repository update"
